### ISSUE TITLE
some questions

### ISSUE THREAD

**Issue by wangyue663** [vidmera/seizure_prediction#1]
Hello, what is the data set used by this epilepsy prediction code? Is it CHB-MIT?

**Comment by ljakupi** [comment]
@wangyue663 [here](https://github.com/ljakupi/sichh_seizure_prediction) you can find some more stuff regarding this prediction task. CHB-MIT is used and some features are calculated on those data. U can find the info there.

**Comment by wangyue663** [comment]
@ljakupi  Thank you very much for your answer, I am a noob, are the patient characteristics generated by your code a picture? Because what I want to study is to generate a two-dimensional image from a one-dimensional signal, thank you very much

**Comment by ljakupi** [comment]
No pictures are created. Other features are used (numeric data) like univariate, SPLV, max correlation, etc.

**Comment by wangyue663** [comment]
thank you very much?@ljakupi
